### PR TITLE
ark, skanlite, spectacle

### PR DESCRIPTION
**Pull request by Dejweed**
Hello!

I added some symlinks for KDE programs. I only added 64 where it looked finished. Also fixed the edit-find icon.

I would love to contribute more, but I'm quite new to git and all that stuff. Do you have any suggestions regarding commits and pull requests? Is it better to commit minor changes here and there or should I wait and then pull request all at once?

Thank you and keep up the good work :)

### CODE REVIEW

**Comment by nestoris** [comment]
Thank you. I'm a newbie too :-) so I also did not fully understand how to check the comparison of changes in graphic (especially svg) files. I'll try to accept the commit, and let's see what happens then :-)

**Comment by nestoris** [comment]
Use this awk-script for quickly and easy making of symlinks in the theme.
https://github.com/nestoris/Scripts/blob/main/iconlink
install it in somewhere in your $PATH, go to directory (for example) SE98/actions and run `iconlink foo foo-symbolic`
or run it without arguments and get help
P.S. only works in trees like `theme/context/size/icon.png`

**Comment by nestoris** [comment]
any contribution is welcome! :-)

**Comment by Dejweed** [comment]
Awesome! Do you keep track of stuff like apps.txt and icons.html or anything else I should be aware of? Also what desktop environment do you use? I'm on kde and I think it would be cool if symbolic icons would change color when using a dark theme (so far default breeze does that), but it uses svg and I did some testing and I would have to replace all pngs with svgs to achieve the same result. I hope that wouldn't break anything with other DEs.

**Comment by nestoris** [comment]
Unfortunately, I can't translate the theme into svg. Because I constantly use pixel graphics, converting png images and ico files back and forth. I work with ico, and then with a program specially written by me, I install the icon formats in the theme folder according to the size. This is closely related to raster graphics. I think you can make a bash or gawk script using the gd library or system-call of Imagemagick to change the color of the icons to match the color of the theme. But I don't have time to do this.
In general, you can write a script that turns all pngs into svgs and put it in the SE98 folder so that every KDE user can convert it by one click if desired.

**Comment by Dejweed** [comment]
Thats ok, I can convert them to svg with Inkscape. I just want to know if thats ok to do or should I just leave it as it is. I'll do some testing beforehand, of course.

**Comment by nestoris** [comment]
Really I want to remove all the svgs :-)
The philosophy of this theme is "raster only". If you can convert the largest formats of icons to replace Chicago95 legacy 48x48 scaled ones it will be good temporary idea, but God willing, I would like to make all the icons in all formats in pixel png. At least in all formats used in GNU.
If you have the Telegram messenger, contact me: `@dobromils` -- it's more convenient for me to have discussions there.

**Pull request merged**
